server:
  port: 8080
  servlet:
    context-path: /airs/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: air
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
